### ISSUE TITLE
Convert SGD GPAD/GPI to GO-CAM TTL files

### ISSUE THREAD

**Issue by dustine32** [geneontology/sgd-go-cams#1]
Ticket for tracking progress of the initial load of SGD Noctua models from standard annotation files. Focusing on major blockers for really getting any models (or a big chunk of them) out of the conversion code in ontobio.

The steps so far include:
1. Validate SGD GPAD and GPI against GO rules using `ontobio-parse-assocs.py` to produce the validated "pristine" GPAD.
2. Convert "pristine" GPAD to TTL using `validate.py -v gpad2gocams`.

I'd say we can close this ticket once the first load of models is pushed to noctua-dev and then open new issues in ontobio for bugs and/or code changes.

Tagging @suzialeksander

**Comment by dustine32** [comment]
@suzialeksander Just noting some things I'm filtering out of the GPAD before the validation step since I'm assuming you don't want these in the GO-CAMs:
* IBAs (`ECO:0000318`)
* IEAs (`ECO:0000501`)

I can keep doing this filtering automatically as part of the bash script or if you wanna filter upstream (like an "import-specific" GPAD) that's cool too.

Anything else I should be blocking from getting into the GO-CAMs?

**Comment by suzialeksander** [comment]
Good call. Let me get back to you on if we want all the rest, or possibly just ones we have actually created.

**Comment by suzialeksander** [comment]
Hey @dustine32 are we looking at the same import file? I only see the codes 

ECO:0000245
ECO:0000247
ECO:0000250
ECO:0000255
ECO:0000266
ECO:0000270
ECO:0000303
ECO:0000304
ECO:0000305
ECO:0000307
ECO:0000314
ECO:0000315
ECO:0000316
ECO:0000353
ECO:0007001
ECO:0007003
ECO:0007005


Test file I'm looking at is from ftp.ebi.ac.uk/pub/contrib/goa/SGD_gpad4noctua.gpa.gz

**Comment by dustine32** [comment]
@suzialeksander Indeed, we are _not_ looking at the same file! I was pulling the GPAD (containing IBAs and IEAs) from:
http://sgd-archive.yeastgenome.org/latest/gpad.sgd.gz
BTW this link appears to be getting updated regularly.

Pulling the GPAD from ftp.ebi.ac.uk/pub/contrib/goa/SGD_gpad4noctua.gpa.gz, right, it doesn't contain any IBAs/IEAs but the file is dated 2022-10-18:
```
!Generated: 2022-10-18 13:02
```
Should we get a more up-to-date file pushed to this `SGD_gpad4noctua.gpa.gz` link?

**Comment by suzialeksander** [comment]
Go ahead and test on this one.  If everything seems to be working, we'll request a fresh file before we go to prod anyway.

**Comment by dustine32** [comment]
Noting here that the `SGD_gpad4noctua.gpa` file uses UniProt IDs for primary object whereas the SGD GPI obviously uses SGD IDs. @suzialeksander I'm assuming the Noctua GO-CAMs will want to use the SGD IDs? We can easily use the SGD GPI's DB_Xref column to match GPAD lines and swap the primary object ID from UniProtKB to SGD. Ex:

Input GPAD (`SGD_gpad4noctua.gpa`) line:
```
UniProtKB:A0A023PXA5            RO:0001025      GO:0005575      GO_REF:0000015  ECO:0000307                     2003-07-30 SGD             id=GOA:2113861687|contributor-id=GOC:Kara Dolinski|creation-date=2015-07-20T12:04:08|modification-date=2015-07-20T12:04:08
```
Input GPI (`gpi.sgd`) line:
```
SGD     S000028729      YAL019W-A               YAL019W-A       protein taxon:559292            UniProtKB:A0A023PXA5       db_subset=Swiss-Prot|go_annotation_complete=20030730|uniprot_proteome=UniProtKB:A0A023PXA5
```
Repaired GPAD line:
```
SGD:S000028729            RO:0001025      GO:0005575      GO_REF:0000015  ECO:0000307                     2003-07-30 SGD             id=GOA:2113861687|contributor-id=GOC:Kara Dolinski|creation-date=2015-07-20T12:04:08|modification-date=2015-07-20T12:04:08
```

**Comment by suzialeksander** [comment]
Yes, this all seems right.  For background, this gpad from EBI is a bit of a one-off (well, on-demand) and there's a WB one in the same `/goa/` directory when they do their import. 

If you can just swap the IDs, definitely please do so.  You're correct that we'll want those to be SGD IDs when we feed it to Noctua.

**Comment by suzialeksander** [comment]
@dustine32  We've asked for a new SGD_gpad4noctua.gpa to be produced when they have time.  It shouldn't make much of a difference for this initial testing load if the annotations are from 2022 or fresh, but just FYI if you suddenly notice a newer file, it's fine.

**Comment by suzialeksander** [comment]
closing as the dev models have been happy for quite some time now.
